Repository julie-forman-kay-lab/IDPConformerGenerator, pull requests merged in 2022-07, with the labels that each got.

#223 Some lint
  CHANGELOG.rst
  src/idpconfgen/__init__.py
  src/idpconfgen/cli.py
  src/idpconfgen/cli_build.py
  src/idpconfgen/cli_csssconv.py
  src/idpconfgen/cli_dssppii.py
  src/idpconfgen/cli_makecsss.py
  src/idpconfgen/cli_merge.py
  src/idpconfgen/cli_search.py
  src/idpconfgen/cli_sethpc.py
  src/idpconfgen/cli_sscalc.py
  src/idpconfgen/cli_ssext.py
  src/idpconfgen/cli_stats.py
  src/idpconfgen/cli_torsions.py
  src/idpconfgen/cli_torsionsJ.py
  src/idpconfgen/cli_validate.py
  src/idpconfgen/components/bgeo_strategies/__init__.py
  src/idpconfgen/components/bgeo_strategies/fixed/__init__.py
  src/idpconfgen/components/bgeo_strategies/int2cart/bgeo_int2cart.py
  src/idpconfgen/components/plots/__init__.py
  src/idpconfgen/components/plots/plotfuncs.py
  src/idpconfgen/components/sidechain_packing/__init__.py
  src/idpconfgen/components/sidechain_packing/mcsce.py
  src/idpconfgen/components/xmer_probs.py
  src/idpconfgen/conformer_generator.py
  src/idpconfgen/core/backbone_torsion_bend_and_distances_analysis_per_residue.py
  src/idpconfgen/core/build_definitions.py
  src/idpconfgen/core/definitions.py
  src/idpconfgen/libs/__init__.py
  src/idpconfgen/libs/libcli.py
  src/idpconfgen/libs/libdownload.py
  src/idpconfgen/libs/libfilter.py
  src/idpconfgen/libs/libhigherlevel.py
  src/idpconfgen/libs/libmulticore.py
  src/idpconfgen/libs/libparse.py
  src/idpconfgen/libs/libplot.py
  src/idpconfgen/libs/libstructure.py
  src/idpconfgen/libs/libtimer.py
  src/idpconfgen/libs/libvalidate.py
  src/idpconfgen/logger.py
  tests/test_build_definitions.py
  tests/test_cli_build.py
  tests/test_libcheck.py
  tests/test_libcli.py
  tests/test_libenergyij.py
  tests/test_libpdb.py
  tests/test_logger.py
  tests/test_multicore.py
  tests/test_search.py
  tests/test_structure.py
  tests/test_xmer_probs.py
  tox.ini
Labels: continuous integration

#226 Correct Redundancies in Loops
  CHANGELOG.rst
  src/idpconfgen/cli_csssconv.py
  src/idpconfgen/cli_sscalc.py
Labels: refactor

#225 Add tests to the `main` function of `cli_build`
  CHANGELOG.rst
  src/idpconfgen/cli_build.py
  src/idpconfgen/cli_csssconv.py
  src/idpconfgen/libs/libhigherlevel.py
  tests/data/idpconfgen_test_db.tgz
  tests/tcommons.py
  tests/test_cli_build.py
Labels: enhancement
