Repository julie-forman-kay-lab/IDPConformerGenerator, pull requests merged in 2023-09, with the labels that each got.

#244 Add more VDW radii and efficiency improvements
  CHANGELOG.rst
  docs/faq.rst
  docs/usage.rst
  example/cnot7_example/README.rst
  example/complex_example/1B34.pdb
  example/complex_example/D1D2.fasta
  example/complex_example/README.rst
  example/slc26a9_example/README.rst
  src/idpconfgen/cli_ldrs.py
  src/idpconfgen/cli_merge.py
  src/idpconfgen/core/definitions.py
  src/idpconfgen/ldrs_helper.py
  src/idpconfgen/libs/libcli.py
  src/idpconfgen/libs/libio.py
  src/idpconfgen/libs/libmultichain.py
  src/idpconfgen/libs/libparse.py
  tests/test_libcli.py
Labels: documentation, enhancement, continuous integration

#245 ``--long`` method of building single chain IDPs
  CHANGELOG.rst
  src/idpconfgen/cli_build.py
  src/idpconfgen/libs/libparse.py
  src/idpconfgen/libs/libpdb.py
Labels: bug, enhancement

#246 Fix unit test error that arose from #245
  CHANGELOG.rst
  src/idpconfgen/cli_build.py
Labels: bug

#248 Update ReadTheDocs config file to v2
  .readthedocs.yaml
  MANIFEST.in
Labels: continuous integration

#251 Update installation and usage documentation
  CHANGELOG.rst
  docs/installation.rst
  example/drksh3_example/README.rst
  example/small_peptide/README.rst
Labels: documentation

#252 Fix MC-SCE integration after PTM feature addition
  CHANGELOG.rst
  example/drksh3_example/README.rst
  src/idpconfgen/components/sidechain_packing/mcsce.py
Labels: bug, documentation
